### PR TITLE
Add first speakers

### PR DESCRIPTION
**Pull request by terezaif**
Screenshot 2021-11-08 at 14 06 50

keynote!!

### CODE REVIEW

**Comment by laysauchoa** [comment]
is this the official photo of the keynote? does he has a colorful version of it? thanks!

**Comment by terezaif** [comment]
> is this the official photo of the keynote? does he has a colorful version of it? thanks!

yeah.. he submitted via the speaker form

**Comment by laysauchoa** [comment]
ok, then we will use this

**Review by sleepypioneer — APPROVED** [review]
:fox_face:

**Pull request merged**
